class Data{
	constructor(){
		this.list =  [
			{phrase: 'The best of both worlds'},
			{phrase: 'A perfect storm'},
			{phrase: 'Barking up the wrong tree'},
			{phrase: 'Every cloud has a silver lining'},
			{phrase: 'Beat around the bush'},
			{phrase: 'A dime a dozen'},
			{phrase: 'Every cloud has a silver lining'},
			{phrase: 'A fool and his money are soon parted'},
			{phrase: 'Back to square one'},
			{phrase: 'An arm and a leg'},
			{phrase: 'Burst your bubble'},
			{phrase: 'A diamond in the rough'},
			{phrase: 'A sight for sore eyes'},
			{phrase: 'An apple a day keeps the doctor away'},
			{phrase: 'Busy as a bee'},
			{phrase: 'Bring home the bacon'},
			{phrase: 'Neither here nor there'},
			{phrase: 'Couch potato'},
			{phrase: 'Look on the bright side'},
			{phrase: 'Better safe than sorry'},
			{phrase: 'Break the ice'},
			{phrase: 'Burst your bubble'},
			{phrase: 'Birds of a feather flock together'},
			{phrase: 'Bull in a china shop'},
			{phrase: 'Backseat driver'},
			{phrase: 'Blast from the past'},
			{phrase: 'Calm before the storm'},
			{phrase: 'Close but no cigar'},
			{phrase: 'Cut to the chase'},
			{phrase: 'Curiosity killed the cat'},
			{phrase: 'Cat got your tongue'},
			{phrase: 'Chip off the old block'},
			{phrase: 'Down for the count'},
			{phrase: 'Deer in headlights'},
			{phrase: 'Dodge a bullet'},
			{phrase: 'Dont hold your breath'},
			{phrase: 'Down in the dumps'},
			{phrase: 'Elephant in the room'},
			{phrase: 'Elvis has left the building'},
			{phrase: 'Even a broken clock is right twice a day'},
			{phrase: 'Everything but the kitchen sink'},
			{phrase: 'Easier said than done'},
			{phrase: 'Every nook and cranny'},
			{phrase: 'Fight fire with fire'},
			{phrase: 'Fish out of water'},
			{phrase: 'Face the music'},
			{phrase: 'Fall on deaf ears'},
			{phrase: 'Frog in your throat'},
			{phrase: 'Go out on a limb'},
			{phrase: 'Get off your high horse'},
			{phrase: 'Get the ball rolling'},
			{phrase: 'Get your act together'},
			{phrase: 'Get off on the wrong foot'},
			{phrase: 'Happy as as clam'},
			{phrase: 'Head over heels'},
			{phrase: 'Hard pill to swallow'},
			{phrase: 'Hung out to dry'},
			{phrase: 'How do you like them apples'},
			{phrase: 'If it aint broke dont fix it'},
			{phrase: 'It aitn over till the fat lady sings'},
			{phrase: 'I spy with my little eye'},
			{phrase: 'In the nick of time'},
			{phrase: 'Jump the gun'},
			{phrase: 'Joined at the hip'},
			{phrase: 'Jump on the bandwagon'},
			{phrase: 'Just what the doctor ordered'},
			{phrase: 'Keep on truckin'},
			{phrase: 'Keep your eyes peeled'},
			{phrase: 'Kill two birds with one stone'},
			{phrase: 'Knock your socks off'},
			{phrase: 'Knock yourself out'},
			{phrase: 'Like father like son'},
			{phrase: 'Long time no see'},
			{phrase: 'Money doesnt grow on trees'},
			{phrase: 'Million dollar question'},
			{phrase: 'More or less'},
			{phrase: 'Monkey see monkey do'},
			{phrase: 'My hands are tied'},
			{phrase: 'Needle in a haystack'},
			{phrase: 'No ifs ands or buts'},
			{phrase: 'Not the sharpest tool in the shed'},
			{phrase: 'No questions asked'},
			{phrase: 'Nine to five'},
			{phrase: 'On cloud nine'},
			{phrase: 'On the same page'},
			{phrase: 'Open a can of worms'},
			{phrase: 'Out of left field'},
			{phrase: 'Once in a blue moon'},
			{phrase: 'Paint the town red'},
			{phrase: 'Playing for keeps'},
			{phrase: 'Par for the course'},
			{phrase: 'Pot calling the kettle black'},
			{phrase: 'Put a sock in it'},
			{phrase: 'Put that in your pipe and smoke it'},
			{phrase: 'Practice makes perfect'},
			{phrase: 'Quick and dirty'},
			{phrase: 'Rain on your parade'},
			{phrase: 'Raining cats and dots'},
			{phrase: 'Read em and weep'},
			{phrase: 'Right off the bat'},
			{phrase: 'Roll with the punches'},
			{phrase: 'Rhyme or reason'},
			{phrase: 'Runnning on fumes'},
			{phrase: 'Short end of the stick'},
			{phrase: 'Shot in the dark'},
			{phrase: 'Slow and steady wins the race'},
			{phrase: 'Son of a gun'},
			{phrase: 'Stick a fork in it'},
			{phrase: 'Spill the beans'},
			{phrase: 'The early bird gets the worm'},
			{phrase: 'The plot thickens'},
			{phrase: 'The straw that broke the camels back'},
			{phrase: 'Throw in the towel'},
			{phrase: 'Two peas in a pod'},
			{phrase: 'Tug of war'},
			{phrase: 'Ugly duckling'},
			{phrase: 'Under your nose'},
			{phrase: 'Up in the air'},
			{phrase: 'Vanished into thin air'},
			{phrase: 'Vice versa'},
			{phrase: 'Wake up call'},
			{phrase: 'What goes up must come down'},
			{phrase: 'Wild goose chase'},
			{phrase: 'Wouldnt harm a fly'},
			{phrase: 'You cant judge a book by its cover'},
			{phrase: 'You can lead a horse to water but you cant make it drink'},
			{phrase: 'You cant teach an old dog new tricks'}
		];
	}
}
